### PR TITLE
Update action_slider_widget.dart

### PR DESCRIPTION
**Pull request by niu-dali**
add  needReverse

### CODE REVIEW

**Comment by niu-dali** [comment]
添加 needReverse 字段，用于在滑动结束时判断是否要倒退动画。
该效果用于验证码的滑块中，如下图所示，滑动结束时，滑块不返回原点，而是停留在原处。

**Comment by maeddin** [comment]
Please create an issue about it. Also, all MRs and Issues should be written in English.

**Comment by niu-dali** [comment]
https://github.com/splashbyte/action_slider/issues/10

**Comment by niu-dali** [comment]
Add a needReverse field to determine if you want to rewind the animation at the end of the slide.
This effect is used in the slider of the captcha, as shown in the image below, when the slide ends, the slider does not return to the origin, but stays in place.

**Comment by maeddin** [comment]
This issue is solved with #16

**Pull request closed without merging**
