### PR TITLE
fixes #11

### LINKED ISSUE #11: This error occurs when my slider finishes executing
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following ArgumentError was thrown building AnimatedBuilder(listenable:
AnimationController#e6f76(▶ 1.000)➩Cubic(0.42, 0.00, 0.58, 1.00), dirty, state:
_AnimatedState#b5ad8):
Invalid argument(s): 0.0

The relevant error-causing widget was:
  AnimatedBuilder
  AnimatedBuilder:file:///Users/lee/.pub-cache/hosted/pub.flutter-io.cn/action_slider-0.7.0/lib/src/action_sli
  der_widget.dart:899:16

When the exception was thrown, this was the stack:
#0      double.clamp (dart:core-patch/double.dart:234:7)
#1      _ActionSliderState.build.<anonymous closure>.<anonymous closure>.statePosToLocalPos
(package:action_slider/src/action_slider_widget.dart:906:46)
#2      _ActionSliderState.build.<anonymous closure>.<anonymous closure>
(package:action_slider/src/action_slider_widget.dart:907:30)
#3      ListenableBuilder.build (package:flutter/src/widgets/transitions.dart:1123:48)
#4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:135:48)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5583:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5471:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5187:7)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2895:19)
#10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:984:21)
#11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:457:5)
#12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
#13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1255:9)
#14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
#15     _invoke (dart:ui/hooks.dart:312:13)
#16     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
#17     _drawFrame (dart:ui/hooks.dart:283:31)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
Another exception was thrown: Invalid argument(s): 0.0
```

### PR DESCRIPTION
**Pull request by maeddin**
closes #11

### CODE REVIEW

**Comment by shihabkandil** [comment]
When it will be merged ? It's working when using this fix.

**Comment by vasilich6107** [comment]
Hey @maeddin 
Could you release this fix in 0.7.1?

**Comment by maeddin** [comment]
@vasilich6107 
You can use 0.8.0-beta.3 from pub.dev.
Unfortunately, I don't have time to officially release 0.8.0 at the moment.

**Comment by vasilich6107** [comment]
0.8.0 has breaking changes
It would be nice to release 0.7.1 from this commit

**Comment by vasilich6107** [comment]
### 0.7.0 was release jul 30 2023

image

### There were no commits after that

image


### The next commit after 0.7.0 release is a bugfix

So we can checkout commit b70507d816b3fb05a946d982c9977d4457652dbe and do the `flutter pub publish`

**Comment by maeddin** [comment]
@vasilich6107 I would rather release 0.8.0 with this fix than release 0.7.1 now. I would recommend migrating to the beta, as you will then be prepared for 0.8.0. Alternatively, you can also reference the commit with the fix directly in your pub.dev file if you don't want to migrate.
I can't just release the commit because the changelog and version are still missing. In the future I will create a separate branch for beta versions so that such fixes can be released afterwards.

**Comment by vasilich6107** [comment]
The steps needed
- checkout the commit
- add changelog entry
- edit version in pubspec.yaml
- run `flutter pub publish`

it's could take 5 mins time at max

**Comment by maeddin** [comment]
@vasilich6107 Every version on pub.dev should also be available on GitHub, especially if it is a stable version. This would not be the case if I edit and upload this version locally. I'm trying to finalize version 0.8.0. What exactly speaks against using the fixed commit? I'm only doing this in my spare time and I'm not going to put unnecessary work into an already outdated version.

**Comment by maeddin** [comment]
@vasilich6107 Why do you not use this in your `pubspec.yaml`?

```
  action_slider:
    git:
      url: https://github.com/splashbyte/action_slider.git
      ref: 348c885ebca5b04b8804ad8bcdef8b13c61df71d
```

**Comment by vasilich6107** [comment]
Yep
i'm already doing this
I'm just asking to help all devs at once by releasing
as far as it should not take too much time

**Pull request merged**
